[build]
  base = "."
  command = "pnpm install && pnpm build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200